name: Deploy VPC Module

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy CloudFormation Template
        run: |
          aws cloudformation deploy \
            --template-file vpc/vpc.yaml \
            --stack-name basic-vpc-stack \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM

