AWSTemplateFormatVersion: '2010-09-09'
Description: A basic VPC module
Resources:
  BasicVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: BasicVPC
